---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cb106.
--- DateTime: 9/17/2020 20:31
---

---@module rom
rom = {}

--TODO: REMOVED
---getfilename: Get the base filename of the ROM loaded.
function rom.getfilename()
end

---gethash: Get a hash of the ROM loaded, for verification. If type is "md5", returns a hex string of the MD5 hash. If type is "base64", returns a base64 string of the MD5 hash, just like the movie romChecksum value.
---@param type string
---@return string
function rom.gethash(type)
end

--TODO: doesn't seem to have individual documentation
---readbyte:
---@param address number
---@return number the number at that address
function rom.readbyte(address)
end

---readbyteunsigned: Get an unsigned byte from the actual ROM file at the given address.
---This includes the header! It's the same as opening the file in a hex-editor.
---@param address number
---@return number
function rom.readbyteunsigned(address)
end

---readbytesigned: Get a signed byte from the actual ROM file at the given address. Returns a byte that is signed.
---This includes the header! It's the same as opening the file in a hex-editor.
---@param address number
---@return number
function rom.readbytesigned(address)
end

---writebyte: Write the value to the ROM at the given address. The value is modded with 256 before writing (so writing 257 will actually write 1). Negative values allowed.
---Editing the header is not available.
---@param address number made up name, the address to write to
---@param value number made up name, the value to write to that address
---@return number the number that was written
function rom.writebyte(address, value)
end
return rom