---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cb106.
--- DateTime: 2/10/2021 21:20
---

function scanModule(module)
    local str = ""
    for k, v in pairs(module) do
        str = str .. k .. " " .. tostring(v) .. "\n"
        print(k .. " " .. tostring(v) .. "\n")
    end
    return str
end

modules = {
    ["fceux"] = {
        ["emu"] = emu,
        ["debugger"] = debugger,
        ["input"] = input,
        ["joypad"] = joypad,
        ["memory"] = memory,
        ["rom"] = rom,
        ["savestate"] = savestate,
        ["zapper"] = zapper,
        ["gui"] = gui,
        ["movie"] = movie,
        ["sound"] = sound,
        ["taseditor"] = taseditor
    },
    ["desmume"] = {
        ["emu"] = emu,
        ["joypad"] = joypad,
        ["savestate"] = savestate,
        ["agg"] = agg,
        ["gui"] = gui,
        ["memory"] = memory,
        ["sound"] = sound,
        ["bit"] = bit,
        ["input"] = input,
        ["movie"] = movie,
        ["stylus"] = stylus
    }
}

for k,v in pairs(_G) do
    print(k)
end

print("point")
MODULE_TO_SCAN = "desmume"
file = io.open("D:\\cb106\\Documents\\GitHub\\Emu-Lua-API\\data\\" .. MODULE_TO_SCAN .. ".md", "w+")
file:write("# " .. MODULE_TO_SCAN .. " #\n")
file:close()
file = io.open("D:\\cb106\\Documents\\GitHub\\Emu-Lua-API\\data\\" .. MODULE_TO_SCAN .. ".md", "a")

print("point")
--print(modules[MODULE_TO_SCAN])
for k, v in pairs(modules[MODULE_TO_SCAN]) do
    print("KEY: " .. k)
    print("VALUE: " .. tostring(v))
    file:write("### " .. k .. " ###\n```java\n" .. scanModule(v) .. "\n```\n")
end

file:close()
